set -g mouse on
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
# Highlight active window's title...
set -g window-status-current-style 'fg=black,bg=blue,bold'
# ...and dim others
set -g window-status-style 'fg=colour244'
# Remove session name from status bar
set -g status-left ''
